name: GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-stats:
    name: Update GitHub Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anuraghazra/github-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_data: last_commit
          commit_message: 'Updated GitHub stats'
          filename: github-stats.svg
          show_icons: true
          theme: default
          hide_border: false
          cache_seconds: 86400 # 24 hours
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Updated GitHub stats'
          branch: ${{ github.ref }}
